#!/usr/bin/env node

/**
 * Bundle Size Checker
 *
 * Reads the stats.json file generated by Angular build and verifies
 * that bundle size thresholds are respected.
 *
 * Usage:
 *   npx ts-node scripts/check-bundle-size.ts
 *   npm run check:bundle
 *
 * Exit codes:
 *   0 = all chunks within budget
 *   1 = one or more chunks exceed budget
 */

import * as fs from 'fs';
import * as path from 'path';

interface BundleStats {
  bundles: Array<{
    name: string;
    size: number;
  }>;
}

// Define bundle size budgets (in bytes)
const BUDGETS = {
  main: 512_000, // 512 KB warn, 1MB error in angular.json
  vendor: 500_000, // vendor bundle
  default: 512_000, // other chunks
};

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

function checkBundleSize(): void {
  const statsPath = path.join(__dirname, '..', 'dist', 'stats.json');

  if (!fs.existsSync(statsPath)) {
    console.error(`❌ Bundle stats file not found: ${statsPath}`);
    console.log('Run `ng build` first to generate stats.json');
    process.exit(1);
  }

  try {
    const rawStats = fs.readFileSync(statsPath, 'utf-8');
    const stats: BundleStats = JSON.parse(rawStats);

    let hasExceeded = false;
    let totalSize = 0;

    console.log('\n📦 Bundle Size Analysis\n');
    console.log('Chunk                           Size        Budget      Status');
    console.log('─'.repeat(70));

    // Sort by size descending
    const sortedBundles = stats.bundles.sort((a, b) => b.size - a.size);

    for (const bundle of sortedBundles) {
      const budget = BUDGETS[bundle.name as keyof typeof BUDGETS] || BUDGETS.default;
      const size = bundle.size;
      const percentage = ((size / budget) * 100).toFixed(1);
      totalSize += size;

      let status = '✅ OK';
      if (size > budget) {
        status = '❌ EXCEEDED';
        hasExceeded = true;
      } else if (size > budget * 0.9) {
        status = '⚠️  WARNING (>90%)';
      }

      const namePadded = bundle.name.padEnd(30);
      const sizePadded = formatBytes(size).padEnd(12);
      const budgetPadded = formatBytes(budget).padEnd(12);

      console.log(`${namePadded} ${sizePadded} ${budgetPadded} ${status} (${percentage}%)`);
    }

    console.log('─'.repeat(70));
    console.log(`Total: ${formatBytes(totalSize)}\n`);

    if (hasExceeded) {
      console.error('❌ One or more bundles exceed their size budget!');
      console.error('   Run `ng build --stats-json` to generate detailed analysis.');
      process.exit(1);
    } else {
      console.log('✅ All bundles are within budget!\n');
      process.exit(0);
    }
  } catch (error) {
    console.error(`❌ Failed to parse stats.json: ${error}`);
    process.exit(1);
  }
}

// Run the check
checkBundleSize();
